Added generic auth rule method for authconfig
Kuadrant/testsuite pull request #130
Opened 2022-10-12 12:57 UTC by jsmolar

2022-10-13 11:06 UTC, azgabur requested changes

2022-10-13 11:06 UTC, azgabur commented on testsuite/openshift/objects/auth_config.py
> +        self.add_auth_rule(name, rule, when)
Missing metrics and priority in add_auth_rule() call

2022-10-13 11:06 UTC, azgabur commented on testsuite/openshift/objects/auth_config.py
>              },
Unused comma

2022-10-13 17:07 UTC, azgabur submitted a review, later dismissed

2022-10-14 06:27 UTC, pehala commented on testsuite/openshift/objects/auth_config.py
> +class Rule:
Just nitpick, since we also define an interface, it should be present there and not only in our implementation(=move it to objects/__init__.py :D)

2022-10-14 10:45 UTC, pehala approved these changes

2022-10-15 14:59 UTC, azgabur approved these changes

2022-10-19 08:17 UTC, merged