Add User RHSSO object
Kuadrant/testsuite pull request #131
Opened 2022-10-14 06:41 UTC by pehala

QoL improvement to RHSSO user manipulation

2022-10-17 13:21 UTC, averevki requested changes

2022-10-17 13:21 UTC, averevki commented on testsuite/oidc/rhsso/objects.py
> -    def assign_realm_role(self, role, user_id: str):
there is one more usage of this method in the `rhsso.test_rhsso_roles.py::user_with_role` fixture

2022-10-17 14:07 UTC, averevki requested changes

2022-10-17 14:07 UTC, averevki commented on testsuite/oidc/rhsso/__init__.py
> +        user_id = self.realm.create_user(self.test_username, self.test_password)
what if `create_user` method would return already initialized `User` class directly instead of his id?

2022-10-19 11:28 UTC, azgabur approved these changes

2022-10-19 11:29 UTC, merged