Added logLevel debug for authorino
Kuadrant/testsuite pull request #134
Opened 2022-10-18 10:23 UTC by jsmolar

2022-10-18 11:49 UTC, dhlavac requested changes
why hardcoding it instead of setting the log level in the configuration file?

2022-10-18 12:37 UTC, jsmolar commented
> why hardcoding it instead of setting the log level in the configuration file?

we can add config file option as well if u insist

2022-10-25 12:16 UTC, pehala approved these changes

2022-10-26 11:20 UTC, dhlavac approved these changes

2022-10-26 11:21 UTC, merged