Update how labels are handles in OpenshiftObjects
Kuadrant/testsuite pull request #185
Opened 2023-03-21 10:02 UTC by pehala

Thanks again @averevki, for suggestion :D

2023-03-21 10:19 UTC, averevki requested changes
One more appearance in the `create_tls_secret` method.

2023-03-21 11:21 UTC, pehala commented
> One more appearance in the `create_tls_secret` method.

fixed

2023-03-21 11:22 UTC, averevki approved these changes

2023-03-23 16:01 UTC, jsmolar approved these changes

2023-03-23 16:05 UTC, merged