Chnage how are OpenShifts processed in the settings
Kuadrant/testsuite pull request #54
Opened 2022-08-23 07:38 UTC by pehala

Change how the OpenShift is loaded in testsuite, now all the processing (e.g. converting it to OpenShiftClient) occurs in the new dynaconf loader and the respective sections in the testconfig are already processed OpenShiftClients.

### Breaking change
Config structure regarding the second OpenShift project was changed.

2022-08-25 09:30 UTC, JaurbanRH approved these changes

2022-08-30 11:44 UTC, dhlavac requested changes

2022-08-30 11:44 UTC, dhlavac commented on config/settings.local.yaml.tpl
> +#    token: "KUADRANT_RULEZ"                   # Optional: API URL for OpenShift, if None it will OpenShift that you are logged in
IMHO wrong comment of token

2022-08-30 12:15 UTC, dhlavac requested changes

2022-08-30 12:15 UTC, dhlavac commented on config/settings.yaml
> +    username: "admin"
where is used ["rhsso"]["username"] ?

2022-08-30 12:21 UTC, dhlavac approved these changes

2022-08-30 12:22 UTC, merged